import { NextRequest, NextResponse } from 'next/server';

// Success story interface
export interface SuccessStory {
  id: string;
  petName: string;
  petType: 'dog' | 'cat' | 'other';
  breed: string;
  age: number;
  ownerName: string;
  location: string;
  transformationType: 'weight-loss' | 'energy' | 'coat-health' | 'digestive' | 'allergies' | 'behavior' | 'overall';
  timeframe: '1-month' | '3-months' | '6-months' | '1-year' | '2-years+';
  beforePhoto: string;
  afterPhoto: string;
  storyText: string;
  healthImprovements: string[];
  weightBefore?: number;
  weightAfter?: number;
  vetApproved: boolean;
  dateSubmitted: string;
  likes: number;
  comments: number;
}

// In-memory storage for success stories
const successStories: Map<string, SuccessStory> = new Map();

// Initialize with 30+ inspiring transformation stories
const initialStories: SuccessStory[] = [
  {
    id: '1',
    petName: 'Max',
    petType: 'dog',
    breed: 'Golden Retriever',
    age: 5,
    ownerName: 'Sarah Johnson',
    location: 'Portland, OR',
    transformationType: 'weight-loss',
    timeframe: '6-months',
    beforePhoto: 'https://images.unsplash.com/photo-1633722715463-d30f4f325e24?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800&h=600&fit=crop',
    storyText: 'Max was 20 pounds overweight and struggling with joint pain. After switching to a raw diet, he lost the extra weight gradually and is now running and playing like a puppy again! His energy levels have completely transformed.',
    healthImprovements: ['Lost 20 lbs', 'Improved joint mobility', 'Increased energy', 'Better coat shine'],
    weightBefore: 95,
    weightAfter: 75,
    vetApproved: true,
    dateSubmitted: '2025-09-15',
    likes: 342,
    comments: 45,
  },
  {
    id: '2',
    petName: 'Luna',
    petType: 'cat',
    breed: 'Maine Coon',
    age: 3,
    ownerName: 'Michael Chen',
    location: 'Seattle, WA',
    transformationType: 'allergies',
    timeframe: '3-months',
    beforePhoto: 'https://images.unsplash.com/photo-1573865526739-10c1dd7cafe4?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1615789591457-74a63395c990?w=800&h=600&fit=crop',
    storyText: 'Luna suffered from constant itching and hair loss from food allergies. Within 3 months on a raw diet, her coat grew back beautifully and the itching stopped completely. She\'s a different cat!',
    healthImprovements: ['Eliminated itching', 'Coat regrowth', 'No more vomiting', 'Increased appetite'],
    vetApproved: true,
    dateSubmitted: '2025-08-22',
    likes: 289,
    comments: 38,
  },
  {
    id: '3',
    petName: 'Buddy',
    petType: 'dog',
    breed: 'Labrador Mix',
    age: 7,
    ownerName: 'Emily Rodriguez',
    location: 'Austin, TX',
    transformationType: 'energy',
    timeframe: '1-month',
    beforePhoto: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&h=600&fit=crop',
    storyText: 'At 7, Buddy was acting like a senior dog - sleeping all day, no interest in walks. Just one month on raw food and he\'s back to acting like a 2-year-old! We go on 3 mile walks daily now.',
    healthImprovements: ['Tripled energy levels', 'Improved muscle tone', 'Better stamina', 'Healthier teeth'],
    weightBefore: 68,
    weightAfter: 65,
    vetApproved: true,
    dateSubmitted: '2025-10-01',
    likes: 412,
    comments: 52,
  },
  {
    id: '4',
    petName: 'Whiskers',
    petType: 'cat',
    breed: 'Domestic Shorthair',
    age: 8,
    ownerName: 'David Kim',
    location: 'San Francisco, CA',
    transformationType: 'digestive',
    timeframe: '3-months',
    beforePhoto: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1606214174585-fe31582dc6ee?w=800&h=600&fit=crop',
    storyText: 'Whiskers had chronic diarrhea and IBD for years. We tried every prescription diet with no success. Raw food changed everything - perfect digestion for 3 months straight!',
    healthImprovements: ['Resolved IBD', 'Normal stools', 'Weight gain', 'More playful'],
    weightBefore: 8,
    weightAfter: 11,
    vetApproved: true,
    dateSubmitted: '2025-09-08',
    likes: 267,
    comments: 41,
  },
  {
    id: '5',
    petName: 'Rocky',
    petType: 'dog',
    breed: 'German Shepherd',
    age: 4,
    ownerName: 'Jennifer Martinez',
    location: 'Denver, CO',
    transformationType: 'coat-health',
    timeframe: '6-months',
    beforePhoto: 'https://images.unsplash.com/photo-1568572933382-74d440642117?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1611003228941-98852ba62227?w=800&h=600&fit=crop',
    storyText: 'Rocky\'s coat was dull and brittle, shedding everywhere. After 6 months on raw, his coat is thick, shiny, and barely sheds. People constantly compliment how beautiful he looks!',
    healthImprovements: ['Shinier coat', 'Reduced shedding by 70%', 'Healthier skin', 'Stronger nails'],
    vetApproved: true,
    dateSubmitted: '2025-08-15',
    likes: 398,
    comments: 36,
  },
  {
    id: '6',
    petName: 'Mittens',
    petType: 'cat',
    breed: 'Persian',
    age: 5,
    ownerName: 'Robert Taylor',
    location: 'Boston, MA',
    transformationType: 'weight-loss',
    timeframe: '1-year',
    beforePhoto: 'https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1548681528-6a5c45b66b42?w=800&h=600&fit=crop',
    storyText: 'Mittens was 18 pounds and could barely groom herself. Through controlled raw feeding, she lost 6 pounds over a year and is now active and happy. She can finally reach all her spots!',
    healthImprovements: ['Lost 6 lbs', 'Improved mobility', 'Better grooming', 'Reduced diabetes risk'],
    weightBefore: 18,
    weightAfter: 12,
    vetApproved: true,
    dateSubmitted: '2025-07-20',
    likes: 324,
    comments: 48,
  },
  {
    id: '7',
    petName: 'Duke',
    petType: 'dog',
    breed: 'Boxer',
    age: 6,
    ownerName: 'Amanda White',
    location: 'Chicago, IL',
    transformationType: 'behavior',
    timeframe: '3-months',
    beforePhoto: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?w=800&h=600&fit=crop',
    storyText: 'Duke was hyperactive and anxious, constantly pacing and whining. The raw diet balanced his energy and mood. He\'s now calm, focused, and so much easier to train!',
    healthImprovements: ['Reduced anxiety', 'Better focus', 'Calmer behavior', 'Improved training response'],
    weightBefore: 72,
    weightAfter: 70,
    vetApproved: true,
    dateSubmitted: '2025-09-28',
    likes: 445,
    comments: 67,
  },
  {
    id: '8',
    petName: 'Shadow',
    petType: 'cat',
    breed: 'Siamese',
    age: 10,
    ownerName: 'Lisa Anderson',
    location: 'Phoenix, AZ',
    transformationType: 'overall',
    timeframe: '6-months',
    beforePhoto: 'https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1472491235688-bdc81a63246e?w=800&h=600&fit=crop',
    storyText: 'At 10, Shadow was declining fast - low energy, poor coat, kidney issues. Raw food gave him a new lease on life. My vet said his kidney values actually improved!',
    healthImprovements: ['Improved kidney function', 'More energy', 'Better coat', 'Gained healthy weight'],
    weightBefore: 9,
    weightAfter: 11,
    vetApproved: true,
    dateSubmitted: '2025-08-05',
    likes: 512,
    comments: 73,
  },
  {
    id: '9',
    petName: 'Bella',
    petType: 'dog',
    breed: 'Beagle',
    age: 3,
    ownerName: 'Chris Brown',
    location: 'Nashville, TN',
    transformationType: 'allergies',
    timeframe: '3-months',
    beforePhoto: 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=800&h=600&fit=crop',
    storyText: 'Bella had terrible skin allergies - constant scratching, red skin, ear infections. Raw food eliminated all her symptoms. No more vet visits for infections!',
    healthImprovements: ['Clear skin', 'No more ear infections', 'Stopped scratching', 'Beautiful coat'],
    vetApproved: true,
    dateSubmitted: '2025-09-12',
    likes: 378,
    comments: 55,
  },
  {
    id: '10',
    petName: 'Oliver',
    petType: 'cat',
    breed: 'British Shorthair',
    age: 4,
    ownerName: 'Patricia Davis',
    location: 'Miami, FL',
    transformationType: 'digestive',
    timeframe: '1-month',
    beforePhoto: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=800&h=600&fit=crop',
    storyText: 'Oliver threw up almost daily on kibble. We were desperate. Within 2 weeks on raw, the vomiting stopped. It\'s been a month with zero issues!',
    healthImprovements: ['No more vomiting', 'Better digestion', 'Increased energy', 'Healthier weight'],
    weightBefore: 13,
    weightAfter: 14,
    vetApproved: true,
    dateSubmitted: '2025-10-08',
    likes: 291,
    comments: 42,
  },
  {
    id: '11',
    petName: 'Zeus',
    petType: 'dog',
    breed: 'Rottweiler',
    age: 5,
    ownerName: 'Mark Wilson',
    location: 'Atlanta, GA',
    transformationType: 'overall',
    timeframe: '1-year',
    beforePhoto: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1567752881298-894bb81f9379?w=800&h=600&fit=crop',
    storyText: 'Zeus had hip dysplasia and was on pain meds daily. After a year on raw with proper supplements, he\'s off medication and runs pain-free. His X-rays show improvement!',
    healthImprovements: ['Reduced joint pain', 'Off pain medication', 'Better mobility', 'Improved X-rays'],
    weightBefore: 115,
    weightAfter: 105,
    vetApproved: true,
    dateSubmitted: '2025-07-10',
    likes: 623,
    comments: 89,
  },
  {
    id: '12',
    petName: 'Cleo',
    petType: 'cat',
    breed: 'Ragdoll',
    age: 6,
    ownerName: 'Sandra Miller',
    location: 'San Diego, CA',
    transformationType: 'energy',
    timeframe: '3-months',
    beforePhoto: 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=800&h=600&fit=crop',
    storyText: 'Cleo was lethargic and slept 20 hours a day. Within 3 months on raw, she became playful and interactive. She actually plays with toys now!',
    healthImprovements: ['More playful', 'Better muscle tone', 'Shinier coat', 'Healthier appetite'],
    weightBefore: 14,
    weightAfter: 13,
    vetApproved: true,
    dateSubmitted: '2025-09-18',
    likes: 334,
    comments: 47,
  },
  {
    id: '13',
    petName: 'Cooper',
    petType: 'dog',
    breed: 'Australian Shepherd',
    age: 2,
    ownerName: 'Kevin Moore',
    location: 'Minneapolis, MN',
    transformationType: 'coat-health',
    timeframe: '3-months',
    beforePhoto: 'https://images.unsplash.com/photo-1568393691622-c7ba131d63b4?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&h=600&fit=crop',
    storyText: 'Cooper had constant hot spots and dry, flaky skin. Raw food transformed his coat completely. No more hot spots, and his fur is softer than ever!',
    healthImprovements: ['Eliminated hot spots', 'Softer coat', 'No more flaky skin', 'Reduced itching'],
    vetApproved: true,
    dateSubmitted: '2025-09-25',
    likes: 287,
    comments: 39,
  },
  {
    id: '14',
    petName: 'Nala',
    petType: 'cat',
    breed: 'Bengal',
    age: 3,
    ownerName: 'Rachel Green',
    location: 'Los Angeles, CA',
    transformationType: 'behavior',
    timeframe: '1-month',
    beforePhoto: 'https://images.unsplash.com/photo-1569591159212-b02ea8a9f239?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1573865526739-10c1dd7cafe4?w=800&h=600&fit=crop',
    storyText: 'Nala was aggressive and would attack without warning. Raw food balanced her mood amazingly. She\'s now affectionate and gentle. It\'s like having a different cat!',
    healthImprovements: ['Calmer temperament', 'Less aggression', 'More affectionate', 'Better sleep patterns'],
    weightBefore: 10,
    weightAfter: 10,
    vetApproved: true,
    dateSubmitted: '2025-10-05',
    likes: 456,
    comments: 71,
  },
  {
    id: '15',
    petName: 'Bear',
    petType: 'dog',
    breed: 'Bernese Mountain Dog',
    age: 4,
    ownerName: 'Thomas Jackson',
    location: 'Seattle, WA',
    transformationType: 'weight-loss',
    timeframe: '1-year',
    beforePhoto: 'https://images.unsplash.com/photo-1558788353-f76d92427f16?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=800&h=600&fit=crop',
    storyText: 'Bear was 40 pounds overweight and struggled to walk. Through carefully portioned raw meals, he lost all the extra weight. He can now hike 5 miles easily!',
    healthImprovements: ['Lost 40 lbs', 'Improved endurance', 'Better joint health', 'Reduced panting'],
    weightBefore: 145,
    weightAfter: 105,
    vetApproved: true,
    dateSubmitted: '2025-06-15',
    likes: 701,
    comments: 95,
  },
  {
    id: '16',
    petName: 'Simba',
    petType: 'cat',
    breed: 'Orange Tabby',
    age: 7,
    ownerName: 'Michelle Lee',
    location: 'Houston, TX',
    transformationType: 'digestive',
    timeframe: '6-months',
    beforePhoto: 'https://images.unsplash.com/photo-1529778873920-4da4926a72c2?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1519052537078-e6302a4968d4?w=800&h=600&fit=crop',
    storyText: 'Simba had pancreatitis and we thought we\'d lose him. Raw food saved his life. His pancreas enzymes are now normal and he\'s thriving!',
    healthImprovements: ['Normal pancreas function', 'No more pain', 'Healthy appetite', 'Active again'],
    weightBefore: 11,
    weightAfter: 13,
    vetApproved: true,
    dateSubmitted: '2025-08-01',
    likes: 534,
    comments: 82,
  },
  {
    id: '17',
    petName: 'Sadie',
    petType: 'dog',
    breed: 'Pit Bull',
    age: 5,
    ownerName: 'Brian Thompson',
    location: 'Philadelphia, PA',
    transformationType: 'allergies',
    timeframe: '6-months',
    beforePhoto: 'https://images.unsplash.com/photo-1514984879728-be0aff75a6e8?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&h=600&fit=crop',
    storyText: 'Sadie\'s allergies were so bad she was on steroids constantly. Raw food broke the cycle. She\'s been steroid-free for 6 months with beautiful skin!',
    healthImprovements: ['Off steroids', 'Clear skin', 'No scratching', 'Full coat regrowth'],
    vetApproved: true,
    dateSubmitted: '2025-07-28',
    likes: 489,
    comments: 64,
  },
  {
    id: '18',
    petName: 'Mochi',
    petType: 'cat',
    breed: 'Scottish Fold',
    age: 4,
    ownerName: 'Jessica Wang',
    location: 'New York, NY',
    transformationType: 'overall',
    timeframe: '3-months',
    beforePhoto: 'https://images.unsplash.com/photo-1478098711619-5ab0b478d6e6?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=800&h=600&fit=crop',
    storyText: 'Mochi had chronic UTIs requiring antibiotics monthly. Since starting raw, she hasn\'t had a single UTI in 3 months. Her urine pH is finally balanced!',
    healthImprovements: ['No UTIs', 'Balanced pH', 'Better hydration', 'Improved litter habits'],
    weightBefore: 9,
    weightAfter: 10,
    vetApproved: true,
    dateSubmitted: '2025-09-20',
    likes: 367,
    comments: 53,
  },
  {
    id: '19',
    petName: 'Diesel',
    petType: 'dog',
    breed: 'Doberman',
    age: 6,
    ownerName: 'Daniel Harris',
    location: 'Dallas, TX',
    transformationType: 'energy',
    timeframe: '1-month',
    beforePhoto: 'https://images.unsplash.com/photo-1477884213360-7e9d7dcc1e48?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1568572933382-74d440642117?w=800&h=600&fit=crop',
    storyText: 'Diesel was sluggish and gaining weight on kibble. One month on raw and his athletic build returned. He\'s fast, lean, and full of energy!',
    healthImprovements: ['Increased stamina', 'Better muscle definition', 'More alert', 'Healthier weight'],
    weightBefore: 88,
    weightAfter: 82,
    vetApproved: true,
    dateSubmitted: '2025-10-02',
    likes: 423,
    comments: 58,
  },
  {
    id: '20',
    petName: 'Princess',
    petType: 'cat',
    breed: 'Calico',
    age: 9,
    ownerName: 'Karen Martinez',
    location: 'Portland, OR',
    transformationType: 'weight-loss',
    timeframe: '1-year',
    beforePhoto: 'https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800&h=600&fit=crop',
    storyText: 'Princess was 22 pounds and pre-diabetic. Through portion-controlled raw feeding, she lost 8 pounds. Her blood sugar is now normal!',
    healthImprovements: ['Lost 8 lbs', 'Normal blood sugar', 'More active', 'Better grooming'],
    weightBefore: 22,
    weightAfter: 14,
    vetApproved: true,
    dateSubmitted: '2025-06-20',
    likes: 556,
    comments: 76,
  },
  {
    id: '21',
    petName: 'Thor',
    petType: 'dog',
    breed: 'Great Dane',
    age: 3,
    ownerName: 'Steven Clark',
    location: 'San Antonio, TX',
    transformationType: 'digestive',
    timeframe: '3-months',
    beforePhoto: 'https://images.unsplash.com/photo-1534361960057-19889db9621e?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=800&h=600&fit=crop',
    storyText: 'Thor had bloat twice and we were terrified. Raw food reduced his bloat risk significantly. He eats slowly now and his digestion is perfect!',
    healthImprovements: ['No bloat episodes', 'Better digestion', 'Slower eating', 'Healthier stools'],
    weightBefore: 152,
    weightAfter: 148,
    vetApproved: true,
    dateSubmitted: '2025-09-05',
    likes: 612,
    comments: 87,
  },
  {
    id: '22',
    petName: 'Misty',
    petType: 'cat',
    breed: 'Russian Blue',
    age: 5,
    ownerName: 'Angela Robinson',
    location: 'Charlotte, NC',
    transformationType: 'coat-health',
    timeframe: '6-months',
    beforePhoto: 'https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=800&h=600&fit=crop',
    storyText: 'Misty\'s beautiful blue coat had become dull and patchy. Raw food brought back the shine and thickness. Everyone asks what I feed her now!',
    healthImprovements: ['Glossy coat', 'No bald patches', 'Softer fur', 'Less shedding'],
    vetApproved: true,
    dateSubmitted: '2025-07-15',
    likes: 378,
    comments: 51,
  },
  {
    id: '23',
    petName: 'Charlie',
    petType: 'dog',
    breed: 'Cocker Spaniel',
    age: 8,
    ownerName: 'Laura Young',
    location: 'Indianapolis, IN',
    transformationType: 'overall',
    timeframe: '6-months',
    beforePhoto: 'https://images.unsplash.com/photo-1546527868-ccb7ee7dfa6a?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?w=800&h=600&fit=crop',
    storyText: 'Charlie had heart disease and limited time. Raw food improved his heart function! My vet couldn\'t believe his echocardiogram results!',
    healthImprovements: ['Improved heart function', 'More energy', 'Better breathing', 'Quality of life'],
    weightBefore: 32,
    weightAfter: 29,
    vetApproved: true,
    dateSubmitted: '2025-08-10',
    likes: 789,
    comments: 104,
  },
  {
    id: '24',
    petName: 'Jasper',
    petType: 'cat',
    breed: 'Tuxedo',
    age: 6,
    ownerName: 'Richard Allen',
    location: 'Columbus, OH',
    transformationType: 'behavior',
    timeframe: '1-month',
    beforePhoto: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=800&h=600&fit=crop',
    storyText: 'Jasper was destroying furniture and yowling at night. Raw food calmed him down completely. He\'s now peaceful and sleeps through the night!',
    healthImprovements: ['Calmer behavior', 'Better sleep', 'No destructive behavior', 'More content'],
    weightBefore: 12,
    weightAfter: 12,
    vetApproved: true,
    dateSubmitted: '2025-10-10',
    likes: 401,
    comments: 62,
  },
  {
    id: '25',
    petName: 'Rosie',
    petType: 'dog',
    breed: 'Cavalier King Charles',
    age: 4,
    ownerName: 'Nancy Scott',
    location: 'Jacksonville, FL',
    transformationType: 'allergies',
    timeframe: '3-months',
    beforePhoto: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=800&h=600&fit=crop',
    storyText: 'Rosie had tear staining and constant eye infections. Raw food cleared it all up! Her face is clean and her eyes are bright and healthy!',
    healthImprovements: ['No tear staining', 'Clear eyes', 'No infections', 'Beautiful face'],
    vetApproved: true,
    dateSubmitted: '2025-09-15',
    likes: 445,
    comments: 69,
  },
  {
    id: '26',
    petName: 'Smokey',
    petType: 'cat',
    breed: 'Gray Tabby',
    age: 11,
    ownerName: 'William Hall',
    location: 'Memphis, TN',
    transformationType: 'overall',
    timeframe: '2-years+',
    beforePhoto: 'https://images.unsplash.com/photo-1503777119540-ce54b422baff?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1472491235688-bdc81a63246e?w=800&h=600&fit=crop',
    storyText: 'Smokey is 11 but raw food turned back the clock! For 2 years he\'s been thriving - jumping, playing, acting like a kitten. Best decision ever!',
    healthImprovements: ['Youthful energy', 'Better mobility', 'Shiny coat', 'Healthy weight'],
    weightBefore: 10,
    weightAfter: 12,
    vetApproved: true,
    dateSubmitted: '2025-05-01',
    likes: 867,
    comments: 118,
  },
  {
    id: '27',
    petName: 'Ace',
    petType: 'dog',
    breed: 'Border Collie',
    age: 2,
    ownerName: 'Kimberly Lewis',
    location: 'Oklahoma City, OK',
    transformationType: 'energy',
    timeframe: '1-month',
    beforePhoto: 'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1568393691622-c7ba131d63b4?w=800&h=600&fit=crop',
    storyText: 'Ace needed proper fuel for agility training. Raw food gave him the sustained energy and focus he needed. We\'re now competing at the national level!',
    healthImprovements: ['Sustained energy', 'Better focus', 'Faster recovery', 'Peak performance'],
    weightBefore: 42,
    weightAfter: 40,
    vetApproved: true,
    dateSubmitted: '2025-09-30',
    likes: 523,
    comments: 74,
  },
  {
    id: '28',
    petName: 'Snowball',
    petType: 'cat',
    breed: 'White Persian',
    age: 7,
    ownerName: 'Dorothy Walker',
    location: 'Las Vegas, NV',
    transformationType: 'digestive',
    timeframe: '6-months',
    beforePhoto: 'https://images.unsplash.com/photo-1573865526739-10c1dd7cafe4?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=800&h=600&fit=crop',
    storyText: 'Snowball had megacolon and needed daily medication. Raw food improved her bowel function so much she only needs meds occasionally now!',
    healthImprovements: ['Better bowel function', 'Less medication', 'More comfortable', 'Better quality of life'],
    weightBefore: 11,
    weightAfter: 12,
    vetApproved: true,
    dateSubmitted: '2025-07-25',
    likes: 434,
    comments: 66,
  },
  {
    id: '29',
    petName: 'Rex',
    petType: 'dog',
    breed: 'German Shepherd Mix',
    age: 9,
    ownerName: 'Gary Turner',
    location: 'Albuquerque, NM',
    transformationType: 'weight-loss',
    timeframe: '1-year',
    beforePhoto: 'https://images.unsplash.com/photo-1546527868-ccb7ee7dfa6a?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1568393691622-c7ba131d63b4?w=800&h=600&fit=crop',
    storyText: 'Rex was 30 pounds overweight at 9 years old. Through raw feeding, he lost it all and regained his youthful mobility. He acts like he\'s 4 again!',
    healthImprovements: ['Lost 30 lbs', 'Improved mobility', 'More playful', 'Better joint health'],
    weightBefore: 110,
    weightAfter: 80,
    vetApproved: true,
    dateSubmitted: '2025-06-01',
    likes: 678,
    comments: 91,
  },
  {
    id: '30',
    petName: 'Patches',
    petType: 'cat',
    breed: 'Tortoiseshell',
    age: 3,
    ownerName: 'Betty Phillips',
    location: 'Tucson, AZ',
    transformationType: 'coat-health',
    timeframe: '3-months',
    beforePhoto: 'https://images.unsplash.com/photo-1569591159212-b02ea8a9f239?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&h=600&fit=crop',
    storyText: 'Patches had dandruff and her coat was rough to touch. Three months on raw and her coat is silky smooth! The dandruff is completely gone.',
    healthImprovements: ['No dandruff', 'Silky coat', 'Healthy skin', 'More grooming'],
    vetApproved: true,
    dateSubmitted: '2025-09-22',
    likes: 356,
    comments: 49,
  },
  {
    id: '31',
    petName: 'Bruno',
    petType: 'dog',
    breed: 'Mastiff',
    age: 5,
    ownerName: 'Frank Campbell',
    location: 'Fresno, CA',
    transformationType: 'overall',
    timeframe: '6-months',
    beforePhoto: 'https://images.unsplash.com/photo-1558788353-f76d92427f16?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=800&h=600&fit=crop',
    storyText: 'Bruno had chronic ear infections and stomach issues. Raw food solved both problems! Six months infection-free and perfect digestion!',
    healthImprovements: ['No ear infections', 'Perfect digestion', 'Better breath', 'More energy'],
    weightBefore: 182,
    weightAfter: 175,
    vetApproved: true,
    dateSubmitted: '2025-08-18',
    likes: 512,
    comments: 78,
  },
  {
    id: '32',
    petName: 'Ginger',
    petType: 'cat',
    breed: 'Orange Tabby',
    age: 8,
    ownerName: 'Helen Parker',
    location: 'Sacramento, CA',
    transformationType: 'energy',
    timeframe: '3-months',
    beforePhoto: 'https://images.unsplash.com/photo-1529778873920-4da4926a72c2?w=800&h=600&fit=crop',
    afterPhoto: 'https://images.unsplash.com/photo-1519052537078-e6302a4968d4?w=800&h=600&fit=crop',
    storyText: 'Ginger was sleeping constantly and gaining weight. Raw food woke her up! She\'s playful, active, and at a healthy weight. Like having a new cat!',
    healthImprovements: ['Increased activity', 'Healthy weight', 'More playful', 'Better mood'],
    weightBefore: 16,
    weightAfter: 12,
    vetApproved: true,
    dateSubmitted: '2025-09-08',
    likes: 423,
    comments: 61,
  },
];

// Initialize the map with stories
initialStories.forEach(story => {
  successStories.set(story.id, story);
});

// GET: Fetch all stories or filtered stories
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const petType = searchParams.get('petType');
    const transformationType = searchParams.get('transformationType');
    const timeframe = searchParams.get('timeframe');
    const sortBy = searchParams.get('sortBy') || 'likes'; // likes, recent, comments

    let stories = Array.from(successStories.values());

    // Apply filters
    if (petType && petType !== 'all') {
      stories = stories.filter(s => s.petType === petType);
    }

    if (transformationType && transformationType !== 'all') {
      stories = stories.filter(s => s.transformationType === transformationType);
    }

    if (timeframe && timeframe !== 'all') {
      stories = stories.filter(s => s.timeframe === timeframe);
    }

    // Sort
    if (sortBy === 'recent') {
      stories.sort((a, b) => new Date(b.dateSubmitted).getTime() - new Date(a.dateSubmitted).getTime());
    } else if (sortBy === 'comments') {
      stories.sort((a, b) => b.comments - a.comments);
    } else {
      stories.sort((a, b) => b.likes - a.likes);
    }

    return NextResponse.json({
      success: true,
      data: stories,
      count: stories.length,
    });
  } catch (error) {
    console.error('Error fetching success stories:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to fetch success stories' },
      { status: 500 }
    );
  }
}

// POST: Submit a new story
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();

    const newStory: SuccessStory = {
      id: Date.now().toString(),
      ...body,
      dateSubmitted: new Date().toISOString().split('T')[0],
      likes: 0,
      comments: 0,
      vetApproved: false,
    };

    successStories.set(newStory.id, newStory);

    return NextResponse.json({
      success: true,
      data: newStory,
    });
  } catch (error) {
    console.error('Error creating success story:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to create success story' },
      { status: 500 }
    );
  }
}
