/**
 * Developer Dashboard - Live MCP Build Monitor
 * Shows real-time code generation from MCP Code Builder
 * Generated by: MCP Code Builder
 * Date: 2025-11-14
 */

'use client';

import { useEffect, useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';

interface BuildTask {
  id: string;
  component: string;
  feature: string;
  status: 'pending' | 'in_progress' | 'completed' | 'failed';
  output?: {
    files: string[];
    logs: string[];
  };
}

interface BuildState {
  status: 'idle' | 'running' | 'completed' | 'failed';
  currentTask: string | null;
  tasks: BuildTask[];
  filesGenerated: string[];
  errors: string[];
  startTime: string | null;
  endTime: string | null;
}

export default function DevDashboard() {
  const [buildState, setBuildState] = useState<BuildState>({
    status: 'idle',
    currentTask: null,
    tasks: [],
    filesGenerated: [],
    errors: [],
    startTime: null,
    endTime: null
  });

  const [connected, setConnected] = useState(false);
  const [socket, setSocket] = useState<WebSocket | null>(null);

  useEffect(() => {
    // Connect to MCP Code Builder WebSocket
    const ws = new WebSocket('ws://10.90.10.82:3100');

    ws.onopen = () => {
      console.log('Connected to MCP Code Builder');
      setConnected(true);
    };

    ws.onmessage = (event) => {
      try {
        const data = JSON.parse(event.data);
        if (data.type === 'build-state') {
          setBuildState(data.state);
        }
      } catch (error) {
        console.error('WebSocket message error:', error);
      }
    };

    ws.onerror = () => {
      setConnected(false);
    };

    ws.onclose = () => {
      setConnected(false);
    };

    setSocket(ws);

    // Cleanup
    return () => {
      if (ws) ws.close();
    };
  }, []);

  const triggerBuild = async () => {
    try {
      const response = await fetch('http://10.90.10.82:3100/api/build', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          bookSlug: 'rawgle',
          pageSlug: 'rawgle-features',
          targetDir: '/home/user/rawgle-frontend/src'
        })
      });

      const result = await response.json();
      console.log('Build triggered:', result);
    } catch (error) {
      console.error('Build trigger error:', error);
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'idle': return 'bg-gray-500';
      case 'running': return 'bg-green-500 animate-pulse';
      case 'completed': return 'bg-blue-500';
      case 'failed': return 'bg-red-500';
      default: return 'bg-gray-500';
    }
  };

  const getTaskStatusColor = (status: string) => {
    switch (status) {
      case 'pending': return 'bg-gray-200 text-gray-700';
      case 'in_progress': return 'bg-yellow-200 text-yellow-800';
      case 'completed': return 'bg-green-200 text-green-800';
      case 'failed': return 'bg-red-200 text-red-800';
      default: return 'bg-gray-200';
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-teal-50 via-white to-orange-50 py-12">
      <div className="container mx-auto px-4 max-w-7xl">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            🚀 MCP Code Builder - Live Dashboard
          </h1>
          <p className="text-lg text-gray-600">
            Watch code being generated in real-time from BookStack specifications
          </p>
          <div className="flex items-center gap-4 mt-4">
            <Badge className={connected ? 'bg-green-500' : 'bg-red-500'}>
              {connected ? '🟢 Connected to MCP Builder' : '🔴 Disconnected'}
            </Badge>
            <Badge className={getStatusColor(buildState.status)}>
              {buildState.status.toUpperCase()}
            </Badge>
          </div>
        </div>

        {/* Controls */}
        <Card className="mb-6">
          <CardHeader>
            <CardTitle>Build Controls</CardTitle>
            <CardDescription>
              Trigger MCP Code Builder to generate features from specifications
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="flex gap-4">
              <button
                onClick={triggerBuild}
                disabled={buildState.status === 'running'}
                className="px-6 py-3 bg-teal-600 text-white rounded-lg font-semibold hover:bg-teal-700 disabled:bg-gray-400 disabled:cursor-not-allowed transition-all"
              >
                {buildState.status === 'running' ? 'Building...' : 'Start Build'}
              </button>
              <button
                onClick={() => window.open('http://10.90.10.82:3100', '_blank')}
                className="px-6 py-3 bg-gray-600 text-white rounded-lg font-semibold hover:bg-gray-700 transition-all"
              >
                Open Full Dashboard →
              </button>
            </div>
          </CardContent>
        </Card>

        {/* Current Task */}
        {buildState.currentTask && (
          <Card className="mb-6 border-l-4 border-teal-500">
            <CardContent className="pt-6">
              <div className="flex items-center gap-3">
                <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-teal-600"></div>
                <span className="text-lg font-semibold text-gray-900">
                  {buildState.currentTask}
                </span>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Statistics */}
        {buildState.tasks.length > 0 && (
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
            <Card>
              <CardContent className="pt-6">
                <div className="text-3xl font-bold text-teal-600">
                  {buildState.tasks.length}
                </div>
                <div className="text-sm text-gray-600">Total Tasks</div>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="pt-6">
                <div className="text-3xl font-bold text-green-600">
                  {buildState.tasks.filter(t => t.status === 'completed').length}
                </div>
                <div className="text-sm text-gray-600">Completed</div>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="pt-6">
                <div className="text-3xl font-bold text-blue-600">
                  {buildState.filesGenerated.length}
                </div>
                <div className="text-sm text-gray-600">Files Generated</div>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="pt-6">
                <div className="text-3xl font-bold text-orange-600">
                  {buildState.startTime ?
                    `${((new Date().getTime() - new Date(buildState.startTime).getTime()) / 1000).toFixed(1)}s`
                    : '0s'
                  }
                </div>
                <div className="text-sm text-gray-600">Build Time</div>
              </CardContent>
            </Card>
          </div>
        )}

        {/* Tasks List */}
        {buildState.tasks.length > 0 && (
          <Card className="mb-6">
            <CardHeader>
              <CardTitle>Build Tasks ({buildState.tasks.length})</CardTitle>
              <CardDescription>
                Real-time task progress from MCP Code Builder
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {buildState.tasks.map((task) => (
                  <div
                    key={task.id}
                    className="p-4 border rounded-lg hover:shadow-md transition-shadow"
                  >
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <div className="text-xs font-semibold text-teal-600 mb-1">
                          {task.component}
                        </div>
                        <div className="font-medium text-gray-900">
                          {task.feature}
                        </div>
                        {task.output?.files && task.output.files.length > 0 && (
                          <div className="mt-2 flex flex-wrap gap-2">
                            {task.output.files.map((file, idx) => (
                              <code
                                key={idx}
                                className="text-xs bg-gray-100 px-2 py-1 rounded"
                              >
                                {file.split('/').pop()}
                              </code>
                            ))}
                          </div>
                        )}
                      </div>
                      <Badge className={getTaskStatusColor(task.status)}>
                        {task.status.replace('_', ' ')}
                      </Badge>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        )}

        {/* Generated Files */}
        {buildState.filesGenerated.length > 0 && (
          <Card>
            <CardHeader>
              <CardTitle>Generated Files ({buildState.filesGenerated.length})</CardTitle>
              <CardDescription>
                Code files created by MCP Code Builder
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-2">
                {buildState.filesGenerated.map((file, idx) => (
                  <div
                    key={idx}
                    className="p-3 bg-green-50 border-l-4 border-green-500 rounded"
                  >
                    <code className="text-sm font-mono text-gray-800">
                      ✅ {file}
                    </code>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        )}

        {/* Empty State */}
        {buildState.tasks.length === 0 && (
          <Card>
            <CardContent className="pt-12 pb-12 text-center">
              <div className="text-6xl mb-4">🚀</div>
              <h3 className="text-2xl font-bold text-gray-900 mb-2">
                Ready to Build
              </h3>
              <p className="text-gray-600 mb-6">
                Click "Start Build" to watch MCP Code Builder generate code from specifications
              </p>
              <button
                onClick={triggerBuild}
                className="px-8 py-4 bg-teal-600 text-white rounded-lg font-semibold text-lg hover:bg-teal-700 transition-all"
              >
                Start Building Code →
              </button>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}
