import { NextResponse } from 'next/server';

// Achievement interface
export interface Achievement {
  id: string;
  title: string;
  description: string;
  category: 'feeding' | 'community' | 'education' | 'health' | 'milestone';
  icon: string;
  isEarned: boolean;
  earnedDate?: string;
  progress?: number;
  maxProgress?: number;
  rarity: 'common' | 'rare' | 'epic' | 'legendary';
}

// In-memory achievements storage - 50+ badges
const achievementsData: Map<string, Achievement> = new Map([
  // FEEDING ACHIEVEMENTS (15)
  ['badge-feed-1', {
    id: 'badge-feed-1',
    title: 'First Raw Meal',
    description: 'Fed your first raw meal',
    category: 'feeding',
    icon: 'utensils',
    isEarned: true,
    earnedDate: '2025-10-15',
    rarity: 'common',
  }],
  ['badge-feed-2', {
    id: 'badge-feed-2',
    title: 'Week Warrior',
    description: 'Completed one week of raw feeding',
    category: 'feeding',
    icon: 'calendar',
    isEarned: true,
    earnedDate: '2025-10-20',
    rarity: 'common',
  }],
  ['badge-feed-3', {
    id: 'badge-feed-3',
    title: 'Month Master',
    description: 'Completed one month of raw feeding',
    category: 'feeding',
    icon: 'calendar-check',
    isEarned: false,
    progress: 18,
    maxProgress: 30,
    rarity: 'rare',
  }],
  ['badge-feed-4', {
    id: 'badge-feed-4',
    title: 'Variety Champion',
    description: 'Fed 10 different protein sources',
    category: 'feeding',
    icon: 'chef-hat',
    isEarned: false,
    progress: 6,
    maxProgress: 10,
    rarity: 'rare',
  }],
  ['badge-feed-5', {
    id: 'badge-feed-5',
    title: 'Organ Expert',
    description: 'Successfully fed all organ types',
    category: 'feeding',
    icon: 'heart-pulse',
    isEarned: false,
    progress: 3,
    maxProgress: 5,
    rarity: 'epic',
  }],
  ['badge-feed-6', {
    id: 'badge-feed-6',
    title: 'Balance Master',
    description: 'Maintained perfect 80/10/10 ratio for a month',
    category: 'feeding',
    icon: 'scales',
    isEarned: false,
    rarity: 'epic',
  }],
  ['badge-feed-7', {
    id: 'badge-feed-7',
    title: 'Bone Broth Pro',
    description: 'Made 10 batches of bone broth',
    category: 'feeding',
    icon: 'soup',
    isEarned: false,
    progress: 1,
    maxProgress: 10,
    rarity: 'rare',
  }],
  ['badge-feed-8', {
    id: 'badge-feed-8',
    title: 'Meal Prep Master',
    description: 'Prepared 50 meals in advance',
    category: 'feeding',
    icon: 'package',
    isEarned: false,
    progress: 8,
    maxProgress: 50,
    rarity: 'epic',
  }],
  ['badge-feed-9', {
    id: 'badge-feed-9',
    title: 'Wild Game Hunter',
    description: 'Fed all exotic proteins',
    category: 'feeding',
    icon: 'mountain',
    isEarned: false,
    rarity: 'legendary',
  }],
  ['badge-feed-10', {
    id: 'badge-feed-10',
    title: 'Seafood Specialist',
    description: 'Fed 10 different fish/seafood proteins',
    category: 'feeding',
    icon: 'fish',
    isEarned: false,
    progress: 2,
    maxProgress: 10,
    rarity: 'rare',
  }],
  ['badge-feed-11', {
    id: 'badge-feed-11',
    title: 'Zero Waste Warrior',
    description: 'Used all parts of animals for 25 meals',
    category: 'feeding',
    icon: 'recycle',
    isEarned: false,
    progress: 4,
    maxProgress: 25,
    rarity: 'epic',
  }],
  ['badge-feed-12', {
    id: 'badge-feed-12',
    title: 'Consistency King',
    description: 'Logged meals for 100 consecutive days',
    category: 'feeding',
    icon: 'trophy',
    isEarned: false,
    rarity: 'legendary',
  }],
  ['badge-feed-13', {
    id: 'badge-feed-13',
    title: 'Portion Perfect',
    description: 'Nailed portion sizes for 30 days',
    category: 'feeding',
    icon: 'ruler',
    isEarned: false,
    rarity: 'rare',
  }],
  ['badge-feed-14', {
    id: 'badge-feed-14',
    title: 'Seasonal Feeder',
    description: 'Fed seasonal proteins for all 4 seasons',
    category: 'feeding',
    icon: 'sun',
    isEarned: false,
    progress: 1,
    maxProgress: 4,
    rarity: 'epic',
  }],
  ['badge-feed-15', {
    id: 'badge-feed-15',
    title: 'Budget Boss',
    description: 'Stayed under budget for 3 months',
    category: 'feeding',
    icon: 'piggy-bank',
    isEarned: false,
    rarity: 'rare',
  }],

  // COMMUNITY ACHIEVEMENTS (12)
  ['badge-comm-1', {
    id: 'badge-comm-1',
    title: 'First Connection',
    description: 'Made your first connection',
    category: 'community',
    icon: 'user-plus',
    isEarned: true,
    earnedDate: '2025-10-16',
    rarity: 'common',
  }],
  ['badge-comm-2', {
    id: 'badge-comm-2',
    title: 'Social Butterfly',
    description: 'Connected with 25 raw feeders',
    category: 'community',
    icon: 'users',
    isEarned: false,
    progress: 7,
    maxProgress: 25,
    rarity: 'rare',
  }],
  ['badge-comm-3', {
    id: 'badge-comm-3',
    title: 'Helpful Hand',
    description: 'Answered 20 community questions',
    category: 'community',
    icon: 'helping-hand',
    isEarned: false,
    progress: 2,
    maxProgress: 20,
    rarity: 'rare',
  }],
  ['badge-comm-4', {
    id: 'badge-comm-4',
    title: 'Recipe Creator',
    description: 'Shared 10 original recipes',
    category: 'community',
    icon: 'book-open',
    isEarned: false,
    progress: 2,
    maxProgress: 10,
    rarity: 'epic',
  }],
  ['badge-comm-5', {
    id: 'badge-comm-5',
    title: 'Photo Pro',
    description: 'Shared 50 meal photos',
    category: 'community',
    icon: 'camera',
    isEarned: false,
    progress: 12,
    maxProgress: 50,
    rarity: 'rare',
  }],
  ['badge-comm-6', {
    id: 'badge-comm-6',
    title: 'Mentor',
    description: 'Helped 10 new raw feeders',
    category: 'community',
    icon: 'award',
    isEarned: false,
    progress: 1,
    maxProgress: 10,
    rarity: 'epic',
  }],
  ['badge-comm-7', {
    id: 'badge-comm-7',
    title: 'Event Organizer',
    description: 'Organized 5 community events',
    category: 'community',
    icon: 'calendar',
    isEarned: false,
    rarity: 'legendary',
  }],
  ['badge-comm-8', {
    id: 'badge-comm-8',
    title: 'Success Story',
    description: 'Shared your transformation story',
    category: 'community',
    icon: 'star',
    isEarned: false,
    rarity: 'common',
  }],
  ['badge-comm-9', {
    id: 'badge-comm-9',
    title: 'Engagement Champion',
    description: 'Liked and commented on 100 posts',
    category: 'community',
    icon: 'message-circle',
    isEarned: false,
    progress: 28,
    maxProgress: 100,
    rarity: 'rare',
  }],
  ['badge-comm-10', {
    id: 'badge-comm-10',
    title: 'Top Contributor',
    description: 'Received 100 likes on your posts',
    category: 'community',
    icon: 'thumbs-up',
    isEarned: false,
    rarity: 'epic',
  }],
  ['badge-comm-11', {
    id: 'badge-comm-11',
    title: 'Trend Setter',
    description: 'Started a viral discussion',
    category: 'community',
    icon: 'trending-up',
    isEarned: false,
    rarity: 'legendary',
  }],
  ['badge-comm-12', {
    id: 'badge-comm-12',
    title: 'Community Champion',
    description: 'Active for 6 consecutive months',
    category: 'community',
    icon: 'shield',
    isEarned: false,
    rarity: 'legendary',
  }],

  // EDUCATION ACHIEVEMENTS (11)
  ['badge-edu-1', {
    id: 'badge-edu-1',
    title: 'First Course',
    description: 'Completed your first course',
    category: 'education',
    icon: 'book',
    isEarned: true,
    earnedDate: '2025-10-18',
    rarity: 'common',
  }],
  ['badge-edu-2', {
    id: 'badge-edu-2',
    title: 'Knowledge Seeker',
    description: 'Completed 10 courses',
    category: 'education',
    icon: 'graduation-cap',
    isEarned: false,
    progress: 2,
    maxProgress: 10,
    rarity: 'rare',
  }],
  ['badge-edu-3', {
    id: 'badge-edu-3',
    title: 'Quiz Master',
    description: 'Scored 100% on 20 quizzes',
    category: 'education',
    icon: 'brain',
    isEarned: false,
    progress: 6,
    maxProgress: 20,
    rarity: 'epic',
  }],
  ['badge-edu-4', {
    id: 'badge-edu-4',
    title: 'Nutrition Expert',
    description: 'Completed advanced nutrition course',
    category: 'education',
    icon: 'microscope',
    isEarned: false,
    rarity: 'epic',
  }],
  ['badge-edu-5', {
    id: 'badge-edu-5',
    title: 'Research Reader',
    description: 'Read 25 scientific articles',
    category: 'education',
    icon: 'file-text',
    isEarned: false,
    progress: 4,
    maxProgress: 25,
    rarity: 'rare',
  }],
  ['badge-edu-6', {
    id: 'badge-edu-6',
    title: 'Workshop Warrior',
    description: 'Attended 10 workshops',
    category: 'education',
    icon: 'video',
    isEarned: false,
    progress: 2,
    maxProgress: 10,
    rarity: 'rare',
  }],
  ['badge-edu-7', {
    id: 'badge-edu-7',
    title: 'Certified Raw Feeder',
    description: 'Completed certification program',
    category: 'education',
    icon: 'badge-check',
    isEarned: false,
    rarity: 'legendary',
  }],
  ['badge-edu-8', {
    id: 'badge-edu-8',
    title: 'Daily Learner',
    description: 'Learned something new for 60 days straight',
    category: 'education',
    icon: 'calendar-days',
    isEarned: false,
    progress: 14,
    maxProgress: 60,
    rarity: 'epic',
  }],
  ['badge-edu-9', {
    id: 'badge-edu-9',
    title: 'Teaching Assistant',
    description: 'Created educational content for others',
    category: 'education',
    icon: 'presentation',
    isEarned: false,
    rarity: 'epic',
  }],
  ['badge-edu-10', {
    id: 'badge-edu-10',
    title: 'Speed Reader',
    description: 'Completed 5 courses in one month',
    category: 'education',
    icon: 'zap',
    isEarned: false,
    rarity: 'rare',
  }],
  ['badge-edu-11', {
    id: 'badge-edu-11',
    title: 'Scholar',
    description: 'Earned all education badges',
    category: 'education',
    icon: 'star',
    isEarned: false,
    rarity: 'legendary',
  }],

  // HEALTH ACHIEVEMENTS (10)
  ['badge-health-1', {
    id: 'badge-health-1',
    title: 'Health Tracker',
    description: 'Logged health metrics for 30 days',
    category: 'health',
    icon: 'heart',
    isEarned: false,
    progress: 8,
    maxProgress: 30,
    rarity: 'rare',
  }],
  ['badge-health-2', {
    id: 'badge-health-2',
    title: 'Weight Watcher',
    description: 'Tracked weight for 12 weeks',
    category: 'health',
    icon: 'activity',
    isEarned: false,
    progress: 4,
    maxProgress: 12,
    rarity: 'rare',
  }],
  ['badge-health-3', {
    id: 'badge-health-3',
    title: 'Vet Partnership',
    description: 'Had 5 vet checkups discussing raw feeding',
    category: 'health',
    icon: 'stethoscope',
    isEarned: false,
    progress: 1,
    maxProgress: 5,
    rarity: 'epic',
  }],
  ['badge-health-4', {
    id: 'badge-health-4',
    title: 'Symptom Tracker',
    description: 'Documented health improvements for 60 days',
    category: 'health',
    icon: 'clipboard',
    isEarned: false,
    progress: 15,
    maxProgress: 60,
    rarity: 'rare',
  }],
  ['badge-health-5', {
    id: 'badge-health-5',
    title: 'Allergy Detective',
    description: 'Successfully identified food allergens',
    category: 'health',
    icon: 'search',
    isEarned: false,
    rarity: 'epic',
  }],
  ['badge-health-6', {
    id: 'badge-health-6',
    title: 'Dental Champion',
    description: 'Documented dental health improvements',
    category: 'health',
    icon: 'smile',
    isEarned: false,
    progress: 5,
    maxProgress: 12,
    rarity: 'rare',
  }],
  ['badge-health-7', {
    id: 'badge-health-7',
    title: 'Transformation',
    description: 'Completed health transformation',
    category: 'health',
    icon: 'trending-up',
    isEarned: false,
    rarity: 'legendary',
  }],
  ['badge-health-8', {
    id: 'badge-health-8',
    title: 'Energy Boost',
    description: 'Documented increased energy levels',
    category: 'health',
    icon: 'battery-charging',
    isEarned: false,
    rarity: 'rare',
  }],
  ['badge-health-9', {
    id: 'badge-health-9',
    title: 'Coat Improvement',
    description: 'Documented shinier coat',
    category: 'health',
    icon: 'sparkles',
    isEarned: false,
    rarity: 'common',
  }],
  ['badge-health-10', {
    id: 'badge-health-10',
    title: 'Wellness Warrior',
    description: 'All health metrics improved',
    category: 'health',
    icon: 'shield-check',
    isEarned: false,
    rarity: 'legendary',
  }],

  // MILESTONE ACHIEVEMENTS (12)
  ['badge-mile-1', {
    id: 'badge-mile-1',
    title: 'Welcome!',
    description: 'Joined RAWGLE',
    category: 'milestone',
    icon: 'sparkles',
    isEarned: true,
    earnedDate: '2025-10-15',
    rarity: 'common',
  }],
  ['badge-mile-2', {
    id: 'badge-mile-2',
    title: 'Getting Started',
    description: 'Completed profile setup',
    category: 'milestone',
    icon: 'user-check',
    isEarned: true,
    earnedDate: '2025-10-15',
    rarity: 'common',
  }],
  ['badge-mile-3', {
    id: 'badge-mile-3',
    title: '100 Points',
    description: 'Earned your first 100 points',
    category: 'milestone',
    icon: 'target',
    isEarned: true,
    earnedDate: '2025-10-17',
    rarity: 'common',
  }],
  ['badge-mile-4', {
    id: 'badge-mile-4',
    title: '500 Points',
    description: 'Reached 500 points',
    category: 'milestone',
    icon: 'target',
    isEarned: false,
    rarity: 'rare',
  }],
  ['badge-mile-5', {
    id: 'badge-mile-5',
    title: '1000 Points',
    description: 'Reached 1000 points',
    category: 'milestone',
    icon: 'target',
    isEarned: false,
    rarity: 'epic',
  }],
  ['badge-mile-6', {
    id: 'badge-mile-6',
    title: '5000 Points',
    description: 'Reached 5000 points',
    category: 'milestone',
    icon: 'trophy',
    isEarned: false,
    rarity: 'legendary',
  }],
  ['badge-mile-7', {
    id: 'badge-mile-7',
    title: 'Level 5',
    description: 'Reached level 5',
    category: 'milestone',
    icon: 'chevrons-up',
    isEarned: false,
    rarity: 'common',
  }],
  ['badge-mile-8', {
    id: 'badge-mile-8',
    title: 'Level 10',
    description: 'Reached level 10',
    category: 'milestone',
    icon: 'chevrons-up',
    isEarned: false,
    rarity: 'rare',
  }],
  ['badge-mile-9', {
    id: 'badge-mile-9',
    title: 'Level 25',
    description: 'Reached level 25',
    category: 'milestone',
    icon: 'crown',
    isEarned: false,
    rarity: 'legendary',
  }],
  ['badge-mile-10', {
    id: 'badge-mile-10',
    title: 'Early Adopter',
    description: 'Joined in the first month',
    category: 'milestone',
    icon: 'rocket',
    isEarned: true,
    earnedDate: '2025-10-15',
    rarity: 'epic',
  }],
  ['badge-mile-11', {
    id: 'badge-mile-11',
    title: 'Streak Master',
    description: 'Logged in for 30 consecutive days',
    category: 'milestone',
    icon: 'flame',
    isEarned: false,
    rarity: 'rare',
  }],
  ['badge-mile-12', {
    id: 'badge-mile-12',
    title: 'RAWGLE Legend',
    description: 'Earned 75% of all badges',
    category: 'milestone',
    icon: 'star',
    isEarned: false,
    rarity: 'legendary',
  }],
]);

export async function GET() {
  const achievements = Array.from(achievementsData.values());

  // Calculate statistics
  const earned = achievements.filter(a => a.isEarned);
  const locked = achievements.filter(a => !a.isEarned);
  const inProgress = locked.filter(a => a.progress && a.progress > 0);

  return NextResponse.json({
    achievements,
    stats: {
      total: achievements.length,
      earned: earned.length,
      locked: locked.length,
      inProgress: inProgress.length,
      percentComplete: Math.round((earned.length / achievements.length) * 100),
      byCategory: {
        feeding: achievements.filter(a => a.category === 'feeding').length,
        community: achievements.filter(a => a.category === 'community').length,
        education: achievements.filter(a => a.category === 'education').length,
        health: achievements.filter(a => a.category === 'health').length,
        milestone: achievements.filter(a => a.category === 'milestone').length,
      },
      byRarity: {
        common: achievements.filter(a => a.rarity === 'common').length,
        rare: achievements.filter(a => a.rarity === 'rare').length,
        epic: achievements.filter(a => a.rarity === 'epic').length,
        legendary: achievements.filter(a => a.rarity === 'legendary').length,
      },
    },
  });
}

export async function POST(request: Request) {
  const body = await request.json();
  const { achievementId, action } = body;

  if (!achievementId) {
    return NextResponse.json({ error: 'Achievement ID required' }, { status: 400 });
  }

  const achievement = achievementsData.get(achievementId);
  if (!achievement) {
    return NextResponse.json({ error: 'Achievement not found' }, { status: 404 });
  }

  // Unlock achievement
  if (action === 'unlock') {
    achievement.isEarned = true;
    achievement.earnedDate = new Date().toISOString().split('T')[0];
    achievementsData.set(achievementId, achievement);
    return NextResponse.json({ success: true, achievement });
  }

  return NextResponse.json({ error: 'Invalid action' }, { status: 400 });
}
